### ISSUE TITLE
注册失败

### ISSUE THREAD

**Issue by R4mble** [igaozp/SSM#3]
你好!我想请问为什么我在点注册的时候会返回400?还望解答,感激不尽.

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by smallminmin** [comment]
是数据库user表的问题，设计了几个字段非空。而注册界面仅仅只能填写账号密码邮件地址。可以参考本人fork后的代码：https://github.com/smallminmin/SSM
