### ISSUE TITLE
新手想学习一番

### ISSUE THREAD

**Issue by LinLeiFeng** [igaozp/SSM#6]
看到这个项目就很感兴趣
这几天一直在认真尝试阅读..
大部分问题解决了 就是requestmapping的时候找不到网页
解决了很久还没有解决...
不知作者能否给个联系方式
请教一下呢
十分感谢！

**Comment by igaozp** [comment]
有什么报错的信息吗？

**Comment by LinLeiFeng** [comment]
我目前出现的问题是：
1.最主要的问题是进行操作无法找到页面，例如增加板块，点添加后就直接报404，应该就没有跳到controller
2.如果通过idea内置打开jsp页面，jsp页面是可以正常显示的，但是通过浏览器直接访问首页就显示404

由于我是初学ssm，想通过您的项目来了解一下
所以项目结构没有做啥修改
唯一的修改就是修改了Modules里的Web Resource Directory
改成了web\Web-info


项目运行没有异常 没有什么致命的错误
但是项目中有以下还是飘红的地方







jar包里的source和javadoc也是红的
由于我还未学习过maven 所以暂时也不知道该如何解决
不知道对项目运行是否有影响


主要问题就是这个拉
您的项目对我的学习有了很大的帮助
如果能运行起来我就能进一步研究了..
感谢您！




------------------ 原始邮件 ------------------
发件人: "Fruent Neon"<notifications@github.com>; 
发送时间: 2019年6月9日(星期天) 晚上10:10
收件人: "igaozp/SSM"<SSM@noreply.github.com>; 
抄送: "　"<www.linchengjian@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [igaozp/SSM] 新手想学习一番 (#6)




有什么报错的信息吗？

**Comment by LinLeiFeng** [comment]
看github这边的图片没有显示，所以我重新发一下吧




<servlet-mapping>
    <servlet-name>dispatcher</servlet-name>
    <url-pattern>/</url-pattern>
</servlet-mapping>


<filter-mapping>
    <filter-name>encodingFilter</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>


这是web.xml
dispatcher和encodingFilter是红的




<mvc:resources location="/WEB-INF/resources/" mapping="/resources/**"/>


这是dispatcher-servlet.xml
其中/WEB-INF/resources/是红的


以及libraries里的每个包的sources和javaDocs都是红的
但是项目可以运行




------------------ 原始邮件 ------------------
发件人: "Fruent Neon"<notifications@github.com>; 
发送时间: 2019年6月9日(星期天) 晚上10:10
收件人: "igaozp/SSM"<SSM@noreply.github.com>; 
抄送: "　"<www.linchengjian@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [igaozp/SSM] 新手想学习一番 (#6)




有什么报错的信息吗？

**Comment by LinLeiFeng** [comment]
不知道您有空的话
能否帮我看看到底是哪里出了差错呢
太感谢了！
